# Configuration for Alacritty, the GPU enhanced terminal emulator

live_config_reload  = true

[env]
TERM  = "xterm-256color"

[window]
decorations  = "Full"
dynamic_padding  = false
opacity  = 0.9
title  = "Terminal"
startup_mode  = "Fullscreen"

[window.padding]
x  = 25
y  = 20

[scrolling]

# Maximum number of lines in the scrollback buffer
history = 10000  # Default: 10000

# Number of lines scrolled for every input scroll increment
multiplier = 3  # Default: 3

[font]
normal = {family = '', style = 'Regular'}
bold = {family = '', style = 'Bold'}
italic = {family = '', style = 'Italic'}
offset = {x = 0, y = 0}
glyph_offset = {x = 0, y = 0}
size = 13.5


[keyboard]
bindings = [
  { key = "V",        mods = "Control|Shift", action = "Paste" },
  { key = "C",        mods = "Control|Shift", action = "Copy" },
  { key = "Paste",                            action = "Paste" },
  { key = "Copy",                             action = "Copy" },
  { key = "Insert",   mods = "Shift",         action = "PasteSelection" },
  { key = "F",        mods = "Control|Shift", action = "SearchForward",     mode = "~Search" },
  { key = "B",        mods = "Control|Shift", action = "SearchBackward",    mode = "~Search" },
  { key = "Key0",     mods = "Control",       action = "ResetFontSize" },
  { key = "Equals",   mods = "Control",       action = "IncreaseFontSize" },
  { key = "Minus",    mods = "Control",       action = "DecreaseFontSize" },
  { key = "Up",       mods = "Shift",         action = "ScrollLineUp",      mode = "~Alt" },
  { key = "Down",     mods = "Shift",         action = "ScrollLineDown",    mode = "~Alt" },
]


# The definition of color schemes.
[colors.primary]
background = '0x282828'
foreground = '0xd4be98'

[colors.normal]
black = '0x3c3836'
red =   '0xea6962'
green = '0xa9b665'
yellow =  '0xd8a657'
blue =  '0x7daea3'
magenta = '0xd3869b'
cyan =  '0x89b482'
white = '0xd4be98'

[colors.bright]
black = '0x3c3836'
red =   '0xea6962'
green = '0xa9b665'
yellow =  '0xd8a657'
blue =  '0x7daea3'
magenta = '0xd3869b'
cyan =  '0x89b482'
white = '0xd4be98'

